//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.MessageSenderSoap")]
    public interface MessageSenderSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 toMobile 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference1.SendSmsResponse SendSms(WindowsFormsApplication1.ServiceReference1.SendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.SendSmsResponse> SendSmsAsync(WindowsFormsApplication1.ServiceReference1.SendSmsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 toOpenId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWeiXin", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference1.SendWeiXinResponse SendWeiXin(WindowsFormsApplication1.ServiceReference1.SendWeiXinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWeiXin", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.SendWeiXinResponse> SendWeiXinAsync(WindowsFormsApplication1.ServiceReference1.SendWeiXinRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 toOpenId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWeiXinForTrade", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference1.SendWeiXinForTradeResponse SendWeiXinForTrade(WindowsFormsApplication1.ServiceReference1.SendWeiXinForTradeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWeiXinForTrade", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.SendWeiXinForTradeResponse> SendWeiXinForTradeAsync(WindowsFormsApplication1.ServiceReference1.SendWeiXinForTradeRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 toOpenId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWeiXinForWarning", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference1.SendWeiXinForWarningResponse SendWeiXinForWarning(WindowsFormsApplication1.ServiceReference1.SendWeiXinForWarningRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWeiXinForWarning", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.SendWeiXinForWarningResponse> SendWeiXinForWarningAsync(WindowsFormsApplication1.ServiceReference1.SendWeiXinForWarningRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 toOpenId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWeiXinForTemplate", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference1.SendWeiXinForTemplateResponse SendWeiXinForTemplate(WindowsFormsApplication1.ServiceReference1.SendWeiXinForTemplateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendWeiXinForTemplate", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.SendWeiXinForTemplateResponse> SendWeiXinForTemplateAsync(WindowsFormsApplication1.ServiceReference1.SendWeiXinForTemplateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSms", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.SendSmsRequestBody Body;
        
        public SendSmsRequest() {
        }
        
        public SendSmsRequest(WindowsFormsApplication1.ServiceReference1.SendSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string toMobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int appId;
        
        public SendSmsRequestBody() {
        }
        
        public SendSmsRequestBody(string toMobile, string content, string userId, int appId) {
            this.toMobile = toMobile;
            this.content = content;
            this.userId = userId;
            this.appId = appId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.SendSmsResponseBody Body;
        
        public SendSmsResponse() {
        }
        
        public SendSmsResponse(WindowsFormsApplication1.ServiceReference1.SendSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSmsResult;
        
        public SendSmsResponseBody() {
        }
        
        public SendSmsResponseBody(string SendSmsResult) {
            this.SendSmsResult = SendSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWeiXinRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWeiXin", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.SendWeiXinRequestBody Body;
        
        public SendWeiXinRequest() {
        }
        
        public SendWeiXinRequest(WindowsFormsApplication1.ServiceReference1.SendWeiXinRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendWeiXinRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string toOpenId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string templateName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string url;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string appId;
        
        public SendWeiXinRequestBody() {
        }
        
        public SendWeiXinRequestBody(string toOpenId, string templateName, string data, string url, string userId, string appId) {
            this.toOpenId = toOpenId;
            this.templateName = templateName;
            this.data = data;
            this.url = url;
            this.userId = userId;
            this.appId = appId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWeiXinResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWeiXinResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.SendWeiXinResponseBody Body;
        
        public SendWeiXinResponse() {
        }
        
        public SendWeiXinResponse(WindowsFormsApplication1.ServiceReference1.SendWeiXinResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendWeiXinResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendWeiXinResult;
        
        public SendWeiXinResponseBody() {
        }
        
        public SendWeiXinResponseBody(string SendWeiXinResult) {
            this.SendWeiXinResult = SendWeiXinResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWeiXinForTradeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWeiXinForTrade", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.SendWeiXinForTradeRequestBody Body;
        
        public SendWeiXinForTradeRequest() {
        }
        
        public SendWeiXinForTradeRequest(WindowsFormsApplication1.ServiceReference1.SendWeiXinForTradeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendWeiXinForTradeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string toOpenId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string url;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int appId;
        
        public SendWeiXinForTradeRequestBody() {
        }
        
        public SendWeiXinForTradeRequestBody(string toOpenId, string data, string url, string userId, int appId) {
            this.toOpenId = toOpenId;
            this.data = data;
            this.url = url;
            this.userId = userId;
            this.appId = appId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWeiXinForTradeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWeiXinForTradeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.SendWeiXinForTradeResponseBody Body;
        
        public SendWeiXinForTradeResponse() {
        }
        
        public SendWeiXinForTradeResponse(WindowsFormsApplication1.ServiceReference1.SendWeiXinForTradeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendWeiXinForTradeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendWeiXinForTradeResult;
        
        public SendWeiXinForTradeResponseBody() {
        }
        
        public SendWeiXinForTradeResponseBody(string SendWeiXinForTradeResult) {
            this.SendWeiXinForTradeResult = SendWeiXinForTradeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWeiXinForWarningRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWeiXinForWarning", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.SendWeiXinForWarningRequestBody Body;
        
        public SendWeiXinForWarningRequest() {
        }
        
        public SendWeiXinForWarningRequest(WindowsFormsApplication1.ServiceReference1.SendWeiXinForWarningRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendWeiXinForWarningRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string toOpenId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string url;
        
        public SendWeiXinForWarningRequestBody() {
        }
        
        public SendWeiXinForWarningRequestBody(string toOpenId, string data, string url) {
            this.toOpenId = toOpenId;
            this.data = data;
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWeiXinForWarningResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWeiXinForWarningResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.SendWeiXinForWarningResponseBody Body;
        
        public SendWeiXinForWarningResponse() {
        }
        
        public SendWeiXinForWarningResponse(WindowsFormsApplication1.ServiceReference1.SendWeiXinForWarningResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendWeiXinForWarningResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendWeiXinForWarningResult;
        
        public SendWeiXinForWarningResponseBody() {
        }
        
        public SendWeiXinForWarningResponseBody(string SendWeiXinForWarningResult) {
            this.SendWeiXinForWarningResult = SendWeiXinForWarningResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWeiXinForTemplateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWeiXinForTemplate", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.SendWeiXinForTemplateRequestBody Body;
        
        public SendWeiXinForTemplateRequest() {
        }
        
        public SendWeiXinForTemplateRequest(WindowsFormsApplication1.ServiceReference1.SendWeiXinForTemplateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendWeiXinForTemplateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string toOpenId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string templateName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string url;
        
        public SendWeiXinForTemplateRequestBody() {
        }
        
        public SendWeiXinForTemplateRequestBody(string toOpenId, string templateName, string data, string url) {
            this.toOpenId = toOpenId;
            this.templateName = templateName;
            this.data = data;
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWeiXinForTemplateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendWeiXinForTemplateResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.SendWeiXinForTemplateResponseBody Body;
        
        public SendWeiXinForTemplateResponse() {
        }
        
        public SendWeiXinForTemplateResponse(WindowsFormsApplication1.ServiceReference1.SendWeiXinForTemplateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendWeiXinForTemplateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendWeiXinForTemplateResult;
        
        public SendWeiXinForTemplateResponseBody() {
        }
        
        public SendWeiXinForTemplateResponseBody(string SendWeiXinForTemplateResult) {
            this.SendWeiXinForTemplateResult = SendWeiXinForTemplateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessageSenderSoapChannel : WindowsFormsApplication1.ServiceReference1.MessageSenderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageSenderSoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference1.MessageSenderSoap>, WindowsFormsApplication1.ServiceReference1.MessageSenderSoap {
        
        public MessageSenderSoapClient() {
        }
        
        public MessageSenderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageSenderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageSenderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageSenderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.SendSmsResponse WindowsFormsApplication1.ServiceReference1.MessageSenderSoap.SendSms(WindowsFormsApplication1.ServiceReference1.SendSmsRequest request) {
            return base.Channel.SendSms(request);
        }
        
        public string SendSms(string toMobile, string content, string userId, int appId) {
            WindowsFormsApplication1.ServiceReference1.SendSmsRequest inValue = new WindowsFormsApplication1.ServiceReference1.SendSmsRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.SendSmsRequestBody();
            inValue.Body.toMobile = toMobile;
            inValue.Body.content = content;
            inValue.Body.userId = userId;
            inValue.Body.appId = appId;
            WindowsFormsApplication1.ServiceReference1.SendSmsResponse retVal = ((WindowsFormsApplication1.ServiceReference1.MessageSenderSoap)(this)).SendSms(inValue);
            return retVal.Body.SendSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.SendSmsResponse> WindowsFormsApplication1.ServiceReference1.MessageSenderSoap.SendSmsAsync(WindowsFormsApplication1.ServiceReference1.SendSmsRequest request) {
            return base.Channel.SendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.SendSmsResponse> SendSmsAsync(string toMobile, string content, string userId, int appId) {
            WindowsFormsApplication1.ServiceReference1.SendSmsRequest inValue = new WindowsFormsApplication1.ServiceReference1.SendSmsRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.SendSmsRequestBody();
            inValue.Body.toMobile = toMobile;
            inValue.Body.content = content;
            inValue.Body.userId = userId;
            inValue.Body.appId = appId;
            return ((WindowsFormsApplication1.ServiceReference1.MessageSenderSoap)(this)).SendSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.SendWeiXinResponse WindowsFormsApplication1.ServiceReference1.MessageSenderSoap.SendWeiXin(WindowsFormsApplication1.ServiceReference1.SendWeiXinRequest request) {
            return base.Channel.SendWeiXin(request);
        }
        
        public string SendWeiXin(string toOpenId, string templateName, string data, string url, string userId, string appId) {
            WindowsFormsApplication1.ServiceReference1.SendWeiXinRequest inValue = new WindowsFormsApplication1.ServiceReference1.SendWeiXinRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.SendWeiXinRequestBody();
            inValue.Body.toOpenId = toOpenId;
            inValue.Body.templateName = templateName;
            inValue.Body.data = data;
            inValue.Body.url = url;
            inValue.Body.userId = userId;
            inValue.Body.appId = appId;
            WindowsFormsApplication1.ServiceReference1.SendWeiXinResponse retVal = ((WindowsFormsApplication1.ServiceReference1.MessageSenderSoap)(this)).SendWeiXin(inValue);
            return retVal.Body.SendWeiXinResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.SendWeiXinResponse> WindowsFormsApplication1.ServiceReference1.MessageSenderSoap.SendWeiXinAsync(WindowsFormsApplication1.ServiceReference1.SendWeiXinRequest request) {
            return base.Channel.SendWeiXinAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.SendWeiXinResponse> SendWeiXinAsync(string toOpenId, string templateName, string data, string url, string userId, string appId) {
            WindowsFormsApplication1.ServiceReference1.SendWeiXinRequest inValue = new WindowsFormsApplication1.ServiceReference1.SendWeiXinRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.SendWeiXinRequestBody();
            inValue.Body.toOpenId = toOpenId;
            inValue.Body.templateName = templateName;
            inValue.Body.data = data;
            inValue.Body.url = url;
            inValue.Body.userId = userId;
            inValue.Body.appId = appId;
            return ((WindowsFormsApplication1.ServiceReference1.MessageSenderSoap)(this)).SendWeiXinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.SendWeiXinForTradeResponse WindowsFormsApplication1.ServiceReference1.MessageSenderSoap.SendWeiXinForTrade(WindowsFormsApplication1.ServiceReference1.SendWeiXinForTradeRequest request) {
            return base.Channel.SendWeiXinForTrade(request);
        }
        
        public string SendWeiXinForTrade(string toOpenId, string data, string url, string userId, int appId) {
            WindowsFormsApplication1.ServiceReference1.SendWeiXinForTradeRequest inValue = new WindowsFormsApplication1.ServiceReference1.SendWeiXinForTradeRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.SendWeiXinForTradeRequestBody();
            inValue.Body.toOpenId = toOpenId;
            inValue.Body.data = data;
            inValue.Body.url = url;
            inValue.Body.userId = userId;
            inValue.Body.appId = appId;
            WindowsFormsApplication1.ServiceReference1.SendWeiXinForTradeResponse retVal = ((WindowsFormsApplication1.ServiceReference1.MessageSenderSoap)(this)).SendWeiXinForTrade(inValue);
            return retVal.Body.SendWeiXinForTradeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.SendWeiXinForTradeResponse> WindowsFormsApplication1.ServiceReference1.MessageSenderSoap.SendWeiXinForTradeAsync(WindowsFormsApplication1.ServiceReference1.SendWeiXinForTradeRequest request) {
            return base.Channel.SendWeiXinForTradeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.SendWeiXinForTradeResponse> SendWeiXinForTradeAsync(string toOpenId, string data, string url, string userId, int appId) {
            WindowsFormsApplication1.ServiceReference1.SendWeiXinForTradeRequest inValue = new WindowsFormsApplication1.ServiceReference1.SendWeiXinForTradeRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.SendWeiXinForTradeRequestBody();
            inValue.Body.toOpenId = toOpenId;
            inValue.Body.data = data;
            inValue.Body.url = url;
            inValue.Body.userId = userId;
            inValue.Body.appId = appId;
            return ((WindowsFormsApplication1.ServiceReference1.MessageSenderSoap)(this)).SendWeiXinForTradeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.SendWeiXinForWarningResponse WindowsFormsApplication1.ServiceReference1.MessageSenderSoap.SendWeiXinForWarning(WindowsFormsApplication1.ServiceReference1.SendWeiXinForWarningRequest request) {
            return base.Channel.SendWeiXinForWarning(request);
        }
        
        public string SendWeiXinForWarning(string toOpenId, string data, string url) {
            WindowsFormsApplication1.ServiceReference1.SendWeiXinForWarningRequest inValue = new WindowsFormsApplication1.ServiceReference1.SendWeiXinForWarningRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.SendWeiXinForWarningRequestBody();
            inValue.Body.toOpenId = toOpenId;
            inValue.Body.data = data;
            inValue.Body.url = url;
            WindowsFormsApplication1.ServiceReference1.SendWeiXinForWarningResponse retVal = ((WindowsFormsApplication1.ServiceReference1.MessageSenderSoap)(this)).SendWeiXinForWarning(inValue);
            return retVal.Body.SendWeiXinForWarningResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.SendWeiXinForWarningResponse> WindowsFormsApplication1.ServiceReference1.MessageSenderSoap.SendWeiXinForWarningAsync(WindowsFormsApplication1.ServiceReference1.SendWeiXinForWarningRequest request) {
            return base.Channel.SendWeiXinForWarningAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.SendWeiXinForWarningResponse> SendWeiXinForWarningAsync(string toOpenId, string data, string url) {
            WindowsFormsApplication1.ServiceReference1.SendWeiXinForWarningRequest inValue = new WindowsFormsApplication1.ServiceReference1.SendWeiXinForWarningRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.SendWeiXinForWarningRequestBody();
            inValue.Body.toOpenId = toOpenId;
            inValue.Body.data = data;
            inValue.Body.url = url;
            return ((WindowsFormsApplication1.ServiceReference1.MessageSenderSoap)(this)).SendWeiXinForWarningAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.SendWeiXinForTemplateResponse WindowsFormsApplication1.ServiceReference1.MessageSenderSoap.SendWeiXinForTemplate(WindowsFormsApplication1.ServiceReference1.SendWeiXinForTemplateRequest request) {
            return base.Channel.SendWeiXinForTemplate(request);
        }
        
        public string SendWeiXinForTemplate(string toOpenId, string templateName, string data, string url) {
            WindowsFormsApplication1.ServiceReference1.SendWeiXinForTemplateRequest inValue = new WindowsFormsApplication1.ServiceReference1.SendWeiXinForTemplateRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.SendWeiXinForTemplateRequestBody();
            inValue.Body.toOpenId = toOpenId;
            inValue.Body.templateName = templateName;
            inValue.Body.data = data;
            inValue.Body.url = url;
            WindowsFormsApplication1.ServiceReference1.SendWeiXinForTemplateResponse retVal = ((WindowsFormsApplication1.ServiceReference1.MessageSenderSoap)(this)).SendWeiXinForTemplate(inValue);
            return retVal.Body.SendWeiXinForTemplateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.SendWeiXinForTemplateResponse> WindowsFormsApplication1.ServiceReference1.MessageSenderSoap.SendWeiXinForTemplateAsync(WindowsFormsApplication1.ServiceReference1.SendWeiXinForTemplateRequest request) {
            return base.Channel.SendWeiXinForTemplateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.SendWeiXinForTemplateResponse> SendWeiXinForTemplateAsync(string toOpenId, string templateName, string data, string url) {
            WindowsFormsApplication1.ServiceReference1.SendWeiXinForTemplateRequest inValue = new WindowsFormsApplication1.ServiceReference1.SendWeiXinForTemplateRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.SendWeiXinForTemplateRequestBody();
            inValue.Body.toOpenId = toOpenId;
            inValue.Body.templateName = templateName;
            inValue.Body.data = data;
            inValue.Body.url = url;
            return ((WindowsFormsApplication1.ServiceReference1.MessageSenderSoap)(this)).SendWeiXinForTemplateAsync(inValue);
        }
    }
}
