server.port: 8088
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://183.2.233.235:1433;DatabaseName=BusinessAssistantDB_Test
    username: BusinessHeplerTestManager
    password: BusinessHeplerTestManager123
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/codeGenerator/*.xml
  type-aliases-package: web.template.entity,web.template.params,web.template.orderBy,web.template.setNullParams
  configuration: 
    map-underscore-to-camel-case: true