server.port: 8088
spring.datasource:
  db1:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://183.2.233.235:1433;DatabaseName=BusinessAssistantDB_Test
    username: BusinessHeplerTestManager
    password: BusinessHeplerTestManager123
projectName: asdasdasdasd
spring.jackson.date-format: yyyy-MM-dd
spring.jackson.time-zone: GMT+8
spring.jackson.serialization.write-dates-as-timestamps: false